name: test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        php-version:
        - "8.0"
        - "7.3"
        - "7.2"
        - "7.1"
        - "7.0"
        - "5.6"
        - "5.5"
        - "5.4"
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: iconv
        tools: composer
    - uses: actions/checkout@v2
    - name: composer install
      run: |
        composer --version
        composer install
    - name: phpunit
      run: |
        vendor/bin/phpunit --version
        vendor/bin/phpunit
    - name: php-cs-fixer fix
      run: |
        vendor/bin/php-cs-fixer --version
        vendor/bin/php-cs-fixer fix --dry-run --verbose --diff
      if: "!startsWith(matrix.php-version, '5.')"
